// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbghldtqvsjvgtqdcgxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZiZ2hsZHRxdnNqdmd0cWRjZ3h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDcwMzksImV4cCI6MjA2NTgyMzAzOX0.lFkiQR_Vrmf-wvyIFa5CckFD3fWl9P72o8i8eQLuGQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);